### ISSUE TITLE
[REQUEST] Adicionar suporte a conteiners

### ISSUE THREAD

**Issue by btd1337** [lucas-a-pelegrino/node-bloodboiler-sequelized#57]
Essa issue tem como objeto solicitar a inclusão de suporte à conteiners ao boilerplate.

Justificativa:

Com a adoção de `conteiners` gasta-se menos tempo para configurar os ambientes e se perde menos tempo analisando e identificando as diferenças existentes.

O resultado é a integração e unificação dos ambientes de trabalho das equipes de desenvolvimento, que aumentam a produtividade.

Com isso, e dentre outros fatores, os conteiners, entende-se aqui o Docker, permite ciclos de entrega de software mais rápidos.

**Comment by lucas-a-pelegrino** [comment]
Opa, docker tá no backlog, devo subir uma versão com docker daqui uns dias. 😁

**Comment by btd1337** [comment]
Fala @lucas-a-pelegrino, blz?

Eu subi a MR https://github.com/lucas-a-pelegrino/node-bloodboiler-sequelized/pull/58 que já tá quase 100%.

Ai se puder, dá apenas umas dicas de como tá funcionando as CI, que eu faço os ajustes pra ela ficar redonda.

**Comment by lucas-a-pelegrino** [comment]
Issue related to PRs #59 #58, it's been closed to the breaking of the guidelines;
